#
#	$Id: 495ed5a87ccf04e5b2d6eb9de67db5aa03384a8f $
#
# Makefile for pre- and cross-compiling .machine files
#
MACHINES=PingPongCLFSM

CLFSM_CXX_ONLY=yes

WANT_CFSM=yes


#.include "../../../../../../mk/fsm.mk"	# comes first: required for compiling state machines

#.include "../../../../../../mk/mipal.mk"	# comes last!

.include "/home/bren/src/MiPal/GUNao/mk/fsm.mk"
.include "/home/bren/src/MiPal/GUNao/mk/mipal.mk"
