import Foundation
import XCTest

@testable import FSM

final class FSMStatusTests: XCTestCase {

    func testAllCases() {
        let expected: Set<FSMStatus> = [
            .executing(transitioned: false),
            .executing(transitioned: true),
            .finished,
            .restarted(transitioned: false),
            .restarted(transitioned: true),
            .restarting,
            .resumed(transitioned: false),
            .resumed(transitioned: true),
            .resuming,
            .suspended(transitioned: false),
            .suspended(transitioned: true),
            .suspending
        ]
        let allCases = Set(FSMStatus.allCases)
        XCTAssertEqual(expected, allCases)
    }

    func testTransitioned() {
        let transitionedStatuses: Set<FSMStatus> = [
            .executing(transitioned: true),
            .restarted(transitioned: true),
            .resumed(transitioned: true),
            .suspended(transitioned: true)
        ]
        for status in transitionedStatuses {
            XCTAssertTrue(status.transitioned)
        }
        for status in FSMStatus.allCases where !transitionedStatuses.contains(status) {
            XCTAssertFalse(status.transitioned)
        }
    }

    func testEquality() {
        let executingFalse = FSMStatus.executing(transitioned: false)
        let executingTrue = FSMStatus.executing(transitioned: true)
        let finished = FSMStatus.finished
        let restartedFalse = FSMStatus.restarted(transitioned: false)
        let restartedTrue = FSMStatus.restarted(transitioned: true)
        let restarting = FSMStatus.restarting
        let resumedFalse = FSMStatus.resumed(transitioned: false)
        let resumedTrue = FSMStatus.resumed(transitioned: true)
        let resuming = FSMStatus.resuming
        let suspendedFalse = FSMStatus.suspended(transitioned: false)
        let suspendedTrue = FSMStatus.suspended(transitioned: true)
        let suspending = FSMStatus.suspending
        XCTAssertEqual(executingFalse, executingFalse)
        XCTAssertNotEqual(executingFalse, executingTrue)
        XCTAssertNotEqual(executingFalse, finished)
        XCTAssertNotEqual(executingFalse, restartedFalse)
        XCTAssertNotEqual(executingFalse, restartedTrue)
        XCTAssertNotEqual(executingFalse, restarting)
        XCTAssertNotEqual(executingFalse, resumedFalse)
        XCTAssertNotEqual(executingFalse, resumedTrue)
        XCTAssertNotEqual(executingFalse, resuming)
        XCTAssertNotEqual(executingFalse, suspendedFalse)
        XCTAssertNotEqual(executingFalse, suspendedTrue)
        XCTAssertNotEqual(executingFalse, suspending)
        XCTAssertNotEqual(executingTrue, executingFalse)
        XCTAssertNotEqual(finished, executingFalse)
        XCTAssertNotEqual(restartedFalse, executingFalse)
        XCTAssertNotEqual(restartedTrue, executingFalse)
        XCTAssertNotEqual(restarting, executingFalse)
        XCTAssertNotEqual(resumedFalse, executingFalse)
        XCTAssertNotEqual(resumedTrue, executingFalse)
        XCTAssertNotEqual(resuming, executingFalse)
        XCTAssertNotEqual(suspendedFalse, executingFalse)
        XCTAssertNotEqual(suspendedTrue, executingFalse)
        XCTAssertNotEqual(suspending, executingFalse)
        XCTAssertEqual(executingTrue, executingTrue)
        XCTAssertNotEqual(executingTrue, executingFalse)
        XCTAssertNotEqual(executingTrue, finished)
        XCTAssertNotEqual(executingTrue, restartedFalse)
        XCTAssertNotEqual(executingTrue, restartedTrue)
        XCTAssertNotEqual(executingTrue, restarting)
        XCTAssertNotEqual(executingTrue, resumedFalse)
        XCTAssertNotEqual(executingTrue, resumedTrue)
        XCTAssertNotEqual(executingTrue, resuming)
        XCTAssertNotEqual(executingTrue, suspendedFalse)
        XCTAssertNotEqual(executingTrue, suspendedTrue)
        XCTAssertNotEqual(executingTrue, suspending)
        XCTAssertNotEqual(executingFalse, executingTrue)
        XCTAssertNotEqual(finished, executingTrue)
        XCTAssertNotEqual(restartedFalse, executingTrue)
        XCTAssertNotEqual(restartedTrue, executingTrue)
        XCTAssertNotEqual(restarting, executingTrue)
        XCTAssertNotEqual(resumedFalse, executingTrue)
        XCTAssertNotEqual(resumedTrue, executingTrue)
        XCTAssertNotEqual(resuming, executingTrue)
        XCTAssertNotEqual(suspendedFalse, executingTrue)
        XCTAssertNotEqual(suspendedTrue, executingTrue)
        XCTAssertNotEqual(suspending, executingTrue)
        XCTAssertEqual(finished, finished)
        XCTAssertNotEqual(finished, executingFalse)
        XCTAssertNotEqual(finished, executingTrue)
        XCTAssertNotEqual(finished, restartedFalse)
        XCTAssertNotEqual(finished, restartedTrue)
        XCTAssertNotEqual(finished, restarting)
        XCTAssertNotEqual(finished, resumedFalse)
        XCTAssertNotEqual(finished, resumedTrue)
        XCTAssertNotEqual(finished, resuming)
        XCTAssertNotEqual(finished, suspendedFalse)
        XCTAssertNotEqual(finished, suspendedTrue)
        XCTAssertNotEqual(finished, suspending)
        XCTAssertNotEqual(finished, executingFalse)
        XCTAssertNotEqual(executingFalse, finished)
        XCTAssertNotEqual(restartedFalse, finished)
        XCTAssertNotEqual(restartedTrue, finished)
        XCTAssertNotEqual(restarting, finished)
        XCTAssertNotEqual(resumedFalse, finished)
        XCTAssertNotEqual(resumedTrue, finished)
        XCTAssertNotEqual(resuming, finished)
        XCTAssertNotEqual(suspendedFalse, finished)
        XCTAssertNotEqual(suspendedTrue, finished)
        XCTAssertNotEqual(suspending, finished)
        XCTAssertEqual(restartedFalse, restartedFalse)
        XCTAssertNotEqual(restartedFalse, executingFalse)
        XCTAssertNotEqual(restartedFalse, executingTrue)
        XCTAssertNotEqual(restartedFalse, finished)
        XCTAssertNotEqual(restartedFalse, restartedTrue)
        XCTAssertNotEqual(restartedFalse, restarting)
        XCTAssertNotEqual(restartedFalse, resumedFalse)
        XCTAssertNotEqual(restartedFalse, resumedTrue)
        XCTAssertNotEqual(restartedFalse, resuming)
        XCTAssertNotEqual(restartedFalse, suspendedFalse)
        XCTAssertNotEqual(restartedFalse, suspendedTrue)
        XCTAssertNotEqual(restartedFalse, suspending)
        XCTAssertNotEqual(executingFalse, restartedFalse)
        XCTAssertNotEqual(executingTrue, restartedFalse)
        XCTAssertNotEqual(finished, restartedFalse)
        XCTAssertNotEqual(restartedTrue, restartedFalse)
        XCTAssertNotEqual(restarting, restartedFalse)
        XCTAssertNotEqual(resumedFalse, restartedFalse)
        XCTAssertNotEqual(resumedTrue, restartedFalse)
        XCTAssertNotEqual(resuming, restartedFalse)
        XCTAssertNotEqual(suspendedFalse, restartedFalse)
        XCTAssertNotEqual(suspendedTrue, restartedFalse)
        XCTAssertNotEqual(suspending, restartedFalse)
        XCTAssertEqual(restartedTrue, restartedTrue)
        XCTAssertNotEqual(restartedTrue, executingFalse)
        XCTAssertNotEqual(restartedTrue, executingTrue)
        XCTAssertNotEqual(restartedTrue, finished)
        XCTAssertNotEqual(restartedTrue, restartedFalse)
        XCTAssertNotEqual(restartedTrue, restarting)
        XCTAssertNotEqual(restartedTrue, resumedFalse)
        XCTAssertNotEqual(restartedTrue, resumedTrue)
        XCTAssertNotEqual(restartedTrue, resuming)
        XCTAssertNotEqual(restartedTrue, suspendedFalse)
        XCTAssertNotEqual(restartedTrue, suspendedTrue)
        XCTAssertNotEqual(restartedTrue, suspending)
        XCTAssertNotEqual(executingFalse, restartedTrue)
        XCTAssertNotEqual(executingTrue, restartedTrue)
        XCTAssertNotEqual(finished, restartedTrue)
        XCTAssertNotEqual(restartedFalse, restartedTrue)
        XCTAssertNotEqual(restarting, restartedTrue)
        XCTAssertNotEqual(resumedFalse, restartedTrue)
        XCTAssertNotEqual(resumedTrue, restartedTrue)
        XCTAssertNotEqual(resuming, restartedTrue)
        XCTAssertNotEqual(suspendedFalse, restartedTrue)
        XCTAssertNotEqual(suspendedTrue, restartedTrue)
        XCTAssertNotEqual(suspending, restartedTrue)
        XCTAssertEqual(restarting, restarting)
        XCTAssertNotEqual(restarting, executingFalse)
        XCTAssertNotEqual(restarting, executingTrue)
        XCTAssertNotEqual(restarting, finished)
        XCTAssertNotEqual(restarting, restartedFalse)
        XCTAssertNotEqual(restarting, restartedTrue)
        XCTAssertNotEqual(restarting, resumedFalse)
        XCTAssertNotEqual(restarting, resumedTrue)
        XCTAssertNotEqual(restarting, resuming)
        XCTAssertNotEqual(restarting, suspendedFalse)
        XCTAssertNotEqual(restarting, suspendedTrue)
        XCTAssertNotEqual(restarting, suspending)
        XCTAssertNotEqual(executingFalse, restarting)
        XCTAssertNotEqual(executingTrue, restarting)
        XCTAssertNotEqual(finished, restarting)
        XCTAssertNotEqual(restartedFalse, restarting)
        XCTAssertNotEqual(restartedTrue, restarting)
        XCTAssertNotEqual(resumedFalse, restarting)
        XCTAssertNotEqual(resumedTrue, restarting)
        XCTAssertNotEqual(resuming, restarting)
        XCTAssertNotEqual(suspendedFalse, restarting)
        XCTAssertNotEqual(suspendedTrue, restarting)
        XCTAssertNotEqual(suspending, restarting)
        XCTAssertEqual(resumedFalse, resumedFalse)
        XCTAssertNotEqual(resumedFalse, executingFalse)
        XCTAssertNotEqual(resumedFalse, executingTrue)
        XCTAssertNotEqual(resumedFalse, finished)
        XCTAssertNotEqual(resumedFalse, restartedFalse)
        XCTAssertNotEqual(resumedFalse, restartedTrue)
        XCTAssertNotEqual(resumedFalse, restarting)
        XCTAssertNotEqual(resumedFalse, resumedTrue)
        XCTAssertNotEqual(resumedFalse, resuming)
        XCTAssertNotEqual(resumedFalse, suspendedFalse)
        XCTAssertNotEqual(resumedFalse, suspendedTrue)
        XCTAssertNotEqual(resumedFalse, suspending)
        XCTAssertNotEqual(executingFalse, resumedFalse)
        XCTAssertNotEqual(executingTrue, resumedFalse)
        XCTAssertNotEqual(finished, resumedFalse)
        XCTAssertNotEqual(restartedFalse, resumedFalse)
        XCTAssertNotEqual(restartedTrue, resumedFalse)
        XCTAssertNotEqual(restarting, resumedFalse)
        XCTAssertNotEqual(resumedTrue, resumedFalse)
        XCTAssertNotEqual(resuming, resumedFalse)
        XCTAssertNotEqual(suspendedFalse, resumedFalse)
        XCTAssertNotEqual(suspendedTrue, resumedFalse)
        XCTAssertNotEqual(suspending, resumedFalse)
        XCTAssertEqual(resumedTrue, resumedTrue)
        XCTAssertNotEqual(resumedTrue, executingFalse)
        XCTAssertNotEqual(resumedTrue, executingTrue)
        XCTAssertNotEqual(resumedTrue, finished)
        XCTAssertNotEqual(resumedTrue, restartedFalse)
        XCTAssertNotEqual(resumedTrue, restartedTrue)
        XCTAssertNotEqual(resumedTrue, restarting)
        XCTAssertNotEqual(resumedTrue, resumedFalse)
        XCTAssertNotEqual(resumedTrue, resuming)
        XCTAssertNotEqual(resumedTrue, suspendedFalse)
        XCTAssertNotEqual(resumedTrue, suspendedTrue)
        XCTAssertNotEqual(resumedTrue, suspending)
        XCTAssertNotEqual(executingFalse, resumedTrue)
        XCTAssertNotEqual(executingTrue, resumedTrue)
        XCTAssertNotEqual(finished, resumedTrue)
        XCTAssertNotEqual(restartedFalse, resumedTrue)
        XCTAssertNotEqual(restartedTrue, resumedTrue)
        XCTAssertNotEqual(restarting, resumedTrue)
        XCTAssertNotEqual(resumedFalse, resumedTrue)
        XCTAssertNotEqual(resuming, resumedTrue)
        XCTAssertNotEqual(suspendedFalse, resumedTrue)
        XCTAssertNotEqual(suspendedTrue, resumedTrue)
        XCTAssertNotEqual(suspending, resumedTrue)
        XCTAssertEqual(resuming, resuming)
        XCTAssertNotEqual(resuming, executingFalse)
        XCTAssertNotEqual(resuming, executingTrue)
        XCTAssertNotEqual(resuming, finished)
        XCTAssertNotEqual(resuming, restartedFalse)
        XCTAssertNotEqual(resuming, restartedTrue)
        XCTAssertNotEqual(resuming, restarting)
        XCTAssertNotEqual(resuming, resumedFalse)
        XCTAssertNotEqual(resuming, resumedTrue)
        XCTAssertNotEqual(resuming, suspendedFalse)
        XCTAssertNotEqual(resuming, suspendedTrue)
        XCTAssertNotEqual(resuming, suspending)
        XCTAssertNotEqual(executingFalse, resuming)
        XCTAssertNotEqual(executingTrue, resuming)
        XCTAssertNotEqual(finished, resuming)
        XCTAssertNotEqual(restartedFalse, resuming)
        XCTAssertNotEqual(restartedTrue, resuming)
        XCTAssertNotEqual(restarting, resuming)
        XCTAssertNotEqual(resumedFalse, resuming)
        XCTAssertNotEqual(resumedTrue, resuming)
        XCTAssertNotEqual(suspendedFalse, resuming)
        XCTAssertNotEqual(suspendedTrue, resuming)
        XCTAssertNotEqual(suspending, resuming)
        XCTAssertEqual(suspendedFalse, suspendedFalse)
        XCTAssertNotEqual(suspendedFalse, executingFalse)
        XCTAssertNotEqual(suspendedFalse, executingTrue)
        XCTAssertNotEqual(suspendedFalse, finished)
        XCTAssertNotEqual(suspendedFalse, restartedFalse)
        XCTAssertNotEqual(suspendedFalse, restartedTrue)
        XCTAssertNotEqual(suspendedFalse, restarting)
        XCTAssertNotEqual(suspendedFalse, resumedFalse)
        XCTAssertNotEqual(suspendedFalse, resumedTrue)
        XCTAssertNotEqual(suspendedFalse, resuming)
        XCTAssertNotEqual(suspendedFalse, suspendedTrue)
        XCTAssertNotEqual(suspendedFalse, suspending)
        XCTAssertNotEqual(executingFalse, suspendedFalse)
        XCTAssertNotEqual(executingTrue, suspendedFalse)
        XCTAssertNotEqual(finished, suspendedFalse)
        XCTAssertNotEqual(restartedFalse, suspendedFalse)
        XCTAssertNotEqual(restartedTrue, suspendedFalse)
        XCTAssertNotEqual(restarting, suspendedFalse)
        XCTAssertNotEqual(resumedFalse, suspendedFalse)
        XCTAssertNotEqual(resumedTrue, suspendedFalse)
        XCTAssertNotEqual(resuming, suspendedFalse)
        XCTAssertNotEqual(suspendedTrue, suspendedFalse)
        XCTAssertNotEqual(suspending, suspendedFalse)
        XCTAssertEqual(suspendedTrue, suspendedTrue)
        XCTAssertNotEqual(suspendedTrue, executingFalse)
        XCTAssertNotEqual(suspendedTrue, executingTrue)
        XCTAssertNotEqual(suspendedTrue, finished)
        XCTAssertNotEqual(suspendedTrue, restartedFalse)
        XCTAssertNotEqual(suspendedTrue, restartedTrue)
        XCTAssertNotEqual(suspendedTrue, restarting)
        XCTAssertNotEqual(suspendedTrue, resumedFalse)
        XCTAssertNotEqual(suspendedTrue, resumedTrue)
        XCTAssertNotEqual(suspendedTrue, resuming)
        XCTAssertNotEqual(suspendedTrue, suspendedFalse)
        XCTAssertNotEqual(suspendedTrue, suspending)
        XCTAssertNotEqual(executingFalse, suspendedTrue)
        XCTAssertNotEqual(executingTrue, suspendedTrue)
        XCTAssertNotEqual(finished, suspendedTrue)
        XCTAssertNotEqual(restartedFalse, suspendedTrue)
        XCTAssertNotEqual(restartedTrue, suspendedTrue)
        XCTAssertNotEqual(restarting, suspendedTrue)
        XCTAssertNotEqual(resumedFalse, suspendedTrue)
        XCTAssertNotEqual(resumedTrue, suspendedTrue)
        XCTAssertNotEqual(resuming, suspendedTrue)
        XCTAssertNotEqual(suspendedFalse, suspendedTrue)
        XCTAssertNotEqual(suspending, suspendedTrue)
        XCTAssertEqual(suspending, suspending)
        XCTAssertNotEqual(suspending, executingFalse)
        XCTAssertNotEqual(suspending, executingTrue)
        XCTAssertNotEqual(suspending, finished)
        XCTAssertNotEqual(suspending, restartedFalse)
        XCTAssertNotEqual(suspending, restartedTrue)
        XCTAssertNotEqual(suspending, restarting)
        XCTAssertNotEqual(suspending, resumedFalse)
        XCTAssertNotEqual(suspending, resumedTrue)
        XCTAssertNotEqual(suspending, resuming)
        XCTAssertNotEqual(suspending, suspendedFalse)
        XCTAssertNotEqual(suspending, suspendedTrue)
        XCTAssertNotEqual(executingFalse, suspending)
        XCTAssertNotEqual(executingTrue, suspending)
        XCTAssertNotEqual(finished, suspending)
        XCTAssertNotEqual(restartedFalse, suspending)
        XCTAssertNotEqual(restartedTrue, suspending)
        XCTAssertNotEqual(restarting, suspending)
        XCTAssertNotEqual(resumedFalse, suspending)
        XCTAssertNotEqual(resumedTrue, suspending)
        XCTAssertNotEqual(resuming, suspending)
        XCTAssertNotEqual(suspendedFalse, suspending)
        XCTAssertNotEqual(suspendedTrue, suspending)
    }

    func testHashable() {
        for status in FSMStatus.allCases {
            var collection = Set<FSMStatus>()
            for status in FSMStatus.allCases {
                XCTAssertFalse(collection.contains(status))
            }
            collection.insert(status)
            XCTAssertTrue(collection.contains(status))
            for otherStatus in FSMStatus.allCases where otherStatus != status {
                XCTAssertFalse(collection.contains(otherStatus))
            }
            collection = Set(FSMStatus.allCases)
            for status in FSMStatus.allCases {
                XCTAssertTrue(collection.contains(status))
            }
            collection.remove(status)
            XCTAssertFalse(collection.contains(status))
            for otherStatus in FSMStatus.allCases where otherStatus != status {
                XCTAssertTrue(collection.contains(otherStatus))
            }
        }
    }

    func testCodable() throws {
        let encoder = JSONEncoder()
        let decoder = JSONDecoder()
        for status in FSMStatus.allCases {
            let result = try decoder.decode(FSMStatus.self, from: encoder.encode(status))
            XCTAssertEqual(status, result)
        }
    }

}
