#
#	$Id: 495ed5a87ccf04e5b2d6eb9de67db5aa03384a8f $
#
# Makefile for pre- and cross-compiling .machine files
#
MACHINES=PingPong #FunctionsTest

CLFSM_CXX_ONLY=yes

WANT_FSM_REFLECTION=yes

.include "../../../../../../mk/fsm.mk"	# comes first: required for compiling state machines

.include "../../../../../../mk/mipal.mk"	# comes last!
