#
#	$Id$
#
# GU localisation module Makefile
#
ALL_TARGETS=build-module
CI_WIP=yes

SWIFT_SRCS!=ls *.swift
SWIFT_BRIDGING_HEADER=IO-Bridging-Header.h


.include "../swiftfsm.mk"
.include "../../../mk/mipal.mk"
